### ISSUE TITLE
What happens after checkout commit (not a branch) work is done?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#1]
Hi all, would like enlightenment on what happens after I had checkout a specific commit in the current branch, and that there are two further commits that exist ahead, then I do some edits on it and "commit" the new changes to it. 

My question is since it is not linked to any branch, where will it be stored?

**Comment by damithc** [comment]
@gweeyc while that commit will be stored somewhere in the git history, it will be unreachable from any branch later. However, there are ways to locate it and move it to an existing branch.
For example, the `git log` command will list all commits (including this one) and the `git cherry-pick` command can be used to copy a commit to another location.

**Comment by gweeyc** [comment]
Thank you! Now it's clearer!
