### ISSUE TITLE
Resolve conflict issue

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#11]
HI Prof Damith,

I did the branch-A-JavaDoc and branch-Level-7 as stipulated. I change the Duke.java private class field of LinkedHashSet to LinkedHashMap meanwhile.

When I first merged the branch-A-JavaDoc to Master, it went well as expected.
When I next try to merge Master to branch-Level-7 i have a merge conflict.

Now how do I manually resolve such a conflict before I merge back the branch-Level-7 to Master again, I want to retain the LinkedHashMap and all the commits of the former branch:

![image](https://user-images.githubusercontent.com/43993134/132665027-81df0524-aa8f-4fd3-bcda-ca4daeaa990f.png)

**Comment by damithc** [comment]
@gweeyc see if [this topic](https://nus-tic4001-ay2122s1.github.io/website/schedule/week4/topics.html#tools-git-and-github-dealing-with-merge-conflicts) from last week helps
The short answer: manually edit the code to remove conflict markers, while keeping the lines you want to keep and deleting the lines you don't want. After that, stage and commit.

**Comment by gweeyc** [comment]
HI Prof Damith,
Thanks for the information. But how do I manually edit which file?

I first checkout the branch-Level-7
Then I open Intellij:
![image](https://user-images.githubusercontent.com/43993134/132695188-e8a98536-36ed-4fc8-a253-7d51267a768a.png)

Does it mean if I delete the conflict coming from the master section, all I have to to is delete that conflict block of code?
![image](https://user-images.githubusercontent.com/43993134/132695667-40ab6bcd-9f01-4007-bc69-ea4f0f9a91d8.png)
Then manually also remove these? 
![image](https://user-images.githubusercontent.com/43993134/132695394-867b055a-47ec-4645-82c2-7441bdc4dcaf.png)
![image](https://user-images.githubusercontent.com/43993134/132695430-01b39134-445c-4da4-be1d-5c7604233283.png)
![image](https://user-images.githubusercontent.com/43993134/132695465-83178326-710d-49f2-a1db-0a72bf0fb278.png)
Then save the file?
Sourcetree will remove the conflict marker automatically for this conflict block?

Thank you for the advice.

**Comment by damithc** [comment]
@gweeyc It is entirely up to you -- you can change the code any way you like as if this is normal editing of code, followed by a normal commit. You can even edit code outside of conflict markers. Removing the conflict markers needs to be done manually too.  If you don't remove it, they will remain in the code.

**Comment by gweeyc** [comment]
Hi Prof Damith,
Thank you for all your kind and prompt tips. I can now resolve the merge conflict successfully!
