### ISSUE TITLE
Intellij Debugger does not show letter in a string's character?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#13]
Hi Prof Damith,
I find the Intellij debugger in the video gives this:
![image](https://user-images.githubusercontent.com/43993134/132938801-cf679a2c-bfa6-48c6-8134-b2ac9102a311.png)

I test out my own Intellij debugger, I see it only shows the ascii value for a character in the string variable:
![image](https://user-images.githubusercontent.com/43993134/132938838-d5c86774-1578-46d0-94f6-32f5283c0337.png)

My query is how do I configure my debugger to also display the character beside its ascii value?

Thank you!

**Comment by damithc** [comment]
@gweeyc There are some solutions suggested in https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009782939-IntelliJ-debugger-variables-shows-in-bytes-instead-of-real-values although there is no definite answer.

**Comment by gweeyc** [comment]
Hi Prof, thanks for the ref, but it does not work for me. But not important for now. Thank you.

**Comment by damithc** [comment]
@gweeyc side note: it's best not to address forum posts to a specific person (unless necessary) as it discourages others from pitching in.
