### ISSUE TITLE
JUnit are we using Gradle or not for this JUnit setup in our iP?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#14]
HI Profs,
![image](https://user-images.githubusercontent.com/43993134/133547543-8e45750f-ef57-4d4f-a07a-973b4c7e74aa.png)

For our J-Unit branch, the J-Unit setup do we choose to do with or without Gradle setup?

Thank you!

**Comment by damithc** [comment]
@gweeyc the default expectation is to go without Gradle, but you are free to use Gradle too, in which case you should do A-Gradle first https://nus-tic4001-ay2122s1.github.io/website/se-book-adapted/projectDuke/index.html#a-gradle

**Comment by gweeyc** [comment]
Thank you for the advice. Will take note.
