### ISSUE TITLE
Cannot publish right the readme.md as webpage?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#16]
Hi Profs,

![image](https://user-images.githubusercontent.com/43993134/133827643-2f9fc748-8e78-43c2-8a5e-2939b47b7bd0.png)

How do I remove the gh-pages which somehow I activated while trying to do the website publish procedure? I need to do the remove else I cannot redo my webpage again?
![image](https://user-images.githubusercontent.com/43993134/133828083-aa99997b-14be-45bb-97a9-b7a811716046.png)

Thank you for your help.

**Comment by damithc** [comment]
@gweeyc Just update your `docs/README.md` and push to your fork; see if [this page](https://gweeyc.github.io/ip/) gets updated accordingly.

**Comment by gweeyc** [comment]
HI Prof Damith,
Seems like there is sth there at the remote site that I need to pull?
![image](https://user-images.githubusercontent.com/43993134/133872510-5e5a36c7-7cb4-4e68-90a6-83ff638255ef.png)


Think somehow this is related to the gh-pages again? So I deleted the gh-pages branch. Now the README.md is referring to this page instead by github:

![image](https://user-images.githubusercontent.com/43993134/133872901-dbdb1bde-a997-4068-a030-f63c347d9d31.png)

How do I get rid of this page so the main /doc save refers to my README.md file instead?

Thanks!

**Comment by damithc** [comment]
Gwee, Yes, when you select a theme for GitHub pages, it creates a commit in your repo. You can just pull it.

**Comment by gweeyc** [comment]
Hi Prof,
Thanks for your help. I now find that all is well if I choose instead of /doc use /root:
![image](https://user-images.githubusercontent.com/43993134/133873171-1135506d-80f2-4f42-b73b-f9b8050bf05f.png)

I find if I choose /doc, it will always point to the /doc that shows the theme page which is not what I want. Is this ok?
However, I have deleted the gh-pages branch, how do I bring back that or it doesn't matter?

**Comment by damithc** [comment]
@gweeyc it should be the `docs` folder, and you should be updating the `docs/README.md` not the `README.md` at the project root. The former is meant for users, while the latter is meant for developers.

**Comment by gweeyc** [comment]
Thanks! Will adjust.
