### ISSUE TITLE
Creating the jar files

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#17]
Hi Profs, classmates,
I find that the jar file created in Intellij does not include data files and test folder ?

For our iP or tP proj, is it ok just to create jar to include only the Main class?

That means user will possibly have to be instructed how to recreate the data and test folders structure and copy the relevant content into them before they can test out these files functionalities?

Is it possible to include all those resources inside a jar file?

Thank you for your advice.

**Comment by damithc** [comment]
> I find that the jar file created in Intellij does not include data files and test folder ?

Yes, that's how it is @gweeyc 

> That means user will possibly have to be instructed how to recreate the data and test folders structure and copy the relevant content into them before they can test out these files functionalities?

Users don't need the test folder, as testing is done by developers, not users.
However, you should tweak your code to create the data folder/file if it doesn't exist. See below:
![image](https://user-images.githubusercontent.com/1673303/133879080-84c31ab9-228c-4a36-9883-a82e8f02d7d7.png)

**Comment by gweeyc** [comment]
Thanks. Got it.
