### ISSUE TITLE
Github Releases source zips updated automatically?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#19]
HI Profs,

![image](https://user-images.githubusercontent.com/43993134/133905882-318b8724-e4b9-4251-8d70-b25663250ecf.png)

I would like to check if the github releases Source code (zip) and Source code (tar.gz) are automatically updated when we update our source code multiple times? 

If not, how do we ensure that, seeing that these files are auto-generated?

Thank you for the advice.

**Comment by damithc** [comment]
> If not, how do we ensure that, seeing that these files are auto-generated?

@gweeyc Not sure myself. You can find out by trial and error. Anyway, not important for this module as we don't use those files.

**Comment by gweeyc** [comment]
Hi Prof Damith,
Thanks! Yeah the Github Documentation here is either sparse or non-existent on the details!

**Comment by gweeyc** [comment]
Hi Prof Damith,
Thanks! Yeah the Github Documentation here is either sparse or non-existent on the details!
