### ISSUE TITLE
Push to fork seems to ask for Github login everytime and a fail message is shown?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#2]
Hi Prof Damith/Prof Boyd,
After completing Level-0, during push a Github Login page appears and i login duly but a failure message is shown next?
![image](https://user-images.githubusercontent.com/43993134/129733894-c0335418-bca9-4dd2-8ed3-5beed529d218.png)

Here is the Level-0 commit screenshot:
![image](https://user-images.githubusercontent.com/43993134/129738070-c340ee1e-0737-4b6d-9a16-8beb834e8490.png)

[* I note there are two separate hunks created by sourcetree that I did not see last time round when I did projects several years back in our previous module, it always show the whole file and the "+" or "-" when I staged the file?]
[* Also the add gradle support red branch is not merged to main branch in the Graph display? Is this ok?]

I checked my remote git, it is correctly logged in, no problem there? Has this to do with recent announcement of Github that login with username and password will be discarded in favour of personal access token, do I need to create one for ip?

I don't understand what is the matter and what it is saying? Thank you for the advice & help!

**Comment by damithc** [comment]
Gwee, try pushing using the command line (i.e., `git push origin master`). If there is an error, post the error message here.
If you are still using the old SourceTree that you installed during TIC2002, make sure you update it first.

**Comment by gweeyc** [comment]
HI Prof Damith,
                         I got an error message like I first thought, Github has changed policy for login:
![image](https://user-images.githubusercontent.com/43993134/129754017-765dfa7f-1b34-49c7-a3cd-4e8a626c8d72.png)

My Sourcetree is latest version 3.4.5 Windows.
I have previously created a personal access token, but how do i use it to login to Github for ip use?
![image](https://user-images.githubusercontent.com/43993134/129755027-3aa1d4a6-a8e8-4b46-88b9-1a2d9dd2052c.png)

Think we are getting there! Just a few more steps...
Thank you!

**Comment by damithc** [comment]
@gweeyc This issue came up in another module I teach, and a solution was found. See https://github.com/nus-cs2103-AY2122S1/forum/issues/13#issuecomment-899985208

**Comment by gweeyc** [comment]
HI Prof Damith,
                        Thanks for the update, yes it works fine now. One last query though:
![image](https://user-images.githubusercontent.com/43993134/129759758-af74190b-4d22-4f6d-8811-0c8dfb5c54b8.png)

How about the add gradle support branch, it seems hanging in mid-air, is it alright, can I ignore it in subsequent work on my projects? That will be all.

Thank you again!

**Comment by damithc** [comment]
> How about the add gradle support branch, it seems hanging in mid-air, is it alright, can I ignore it in subsequent work on my projects?

Yes, you can ignore it for now @gweeyc. We'll start using it at a later week.

**Comment by gweeyc** [comment]
Noted and thanks!
