### ISSUE TITLE
How to add a forked repo to a team?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#20]
Hi Profs, classmates,
I try out the exercise on team org and team repo, but hit a snack when asked to add the forked repo to developers team.

In the organization team-org21 I created, I cannot add the forked repo to the developers team at all? I try the url or the git reference also will not work?

Thank you for the help!

**Comment by damithc** [comment]
@gweeyc can you post a screenshot of the page in concern?

**Comment by gweeyc** [comment]
HI Profs,
I don't know how it works again, but I find that I just need to type sam and the search will detect and fill in the rest of the forked repo! So now I can add it to my team! Weird, seems like the search box must detect first the forked repo, then I can add.

Thanks, problem solved!
