### ISSUE TITLE
Why add the forked repo to the developers team?

### ISSUE THREAD

**Issue by ycghub** [nus-tic4001-AY2122S1/forum#21]
Hi Profs,
I am not sure why one is to add the forked repo (team repo) to the developers team?
![team_repo](https://user-images.githubusercontent.com/91125814/134162557-35fc1eff-581f-4cc8-8a69-256c7793f4b9.jpg) 

The instruction in the textbook:
![fork_repo_add](https://user-images.githubusercontent.com/91125814/134162779-9802eca7-1806-4a77-8d4d-5ac9a94bae8e.jpg)

I see that a team member still need to do another manual fork from the organization team repo?
What does the adding of the forked repo to the developers team do or enable actually? Write permission?

Thank you for the advice.

**Comment by damithc** [comment]
> What does the adding of the forked repo to the developers team do or enable actually? Write permission?

Yes, that's the main reason @ycghub. The workflow we'll be using (called the _forking_ workflow) does not require all members to have write permissions to the main team repository, thus reducing the risk of accidental messing up of the team repository.  After you use that workflow for a while, you can switch to a simpler workflow that bypasses the forks and push directly to the team repository if you want.

**Comment by ycghub** [comment]
Thanks, prof Damith.
