### ISSUE TITLE
There seems to be no Github Actions enable button?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#24]
Hi Profs,
![image](https://user-images.githubusercontent.com/43993134/134794763-d7ef4017-a297-4ed4-b3f4-643c9e6e7ac0.png)

In the setup instructions above, there is a button, but now I cannot find any on GitHub.

What I see under Actions tab is this:
![image](https://user-images.githubusercontent.com/43993134/134794800-fb70bba7-bf41-490c-860a-c2445c0f3d7e.png)

What shall we do with the suggested workflow, if any?

Thanks!

**Comment by damithc** [comment]
@gweeyc Looks like GitHub changed that page. Ignore that instructions for the time being.

**Comment by gweeyc** [comment]
Thanks!
