### ISSUE TITLE
How to assign admin or write to developers team members on the forked repo?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#25]
HI Profs,
I did the add a try out forked repo successful to my developers team:
![image](https://user-images.githubusercontent.com/43993134/135071807-424e01b2-9918-404d-a6ef-f9ecdbe45274.png)

But I see the permission is set on the repo itself and not on individual people who access it. If I say select write permission, that all members in the developers team will have write permission, then how to tune it so say two of the team members are to be given the admin permission instead as I see no option around to do that?

Thanks!

**Comment by damithc** [comment]
> But I see the permission is set on the repo itself and not on individual people who access it. If I say select write permission, that all members in the developers team will have write permission, then how to tune it so say two of the team members are to be given the admin permission instead as I see no option around to do that?

@gweeyc I think all members of a GitHub team will have the same level of permissions. If you want to give different permissions, you can create different teams e.g., `admins`, `devs`

**Comment by gweeyc** [comment]
Oh ok, thanks Prof, get it.
