### ISSUE TITLE
checkstyle.xml and build.gradle file some errors?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#26]
Hi Profs,
![image](https://user-images.githubusercontent.com/43993134/135090089-8a660f5d-415a-4686-922f-bf3e663d84ef.png)

Like to check if this error reporting in Intellij is something to ignore or corrected?

Here is another error log on checkstyle.xml:
![image](https://user-images.githubusercontent.com/43993134/135090358-2d8419e5-5a44-4d9d-b691-287df2e170c7.png)

**Comment by damithc** [comment]
@gweeyc Can ignore for now. We can observe for a while to see if they affect anything that matters.

**Comment by gweeyc** [comment]
Noted.
