### ISSUE TITLE
Why !Docs Published is not detected?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#27]
Hi Profs,

![image](https://user-images.githubusercontent.com/43993134/135121378-a4532f2a-7e26-481b-8806-77a99768798a.png)

1) For our team 4, we have activated the github-pages fine, but it is not detected?

![image](https://user-images.githubusercontent.com/43993134/135122339-f1d30df9-b46f-446c-8acd-d45b746c331b.png)

2) Is it correct to activate the Github pages on our Organization forked repo? We notice that our local clone repo has no Github pages activated at all.

3) Lastly, we do not know why the Java CI |passing missing the CI status done? What do we need to do here?

Thank you!

**Comment by damithc** [comment]
@gweeyc post a screenshot of your team repo's GitHub pages setting.
You can push a trivial commit to the team repo to see if it triggers Github Actions.

**Comment by gweeyc** [comment]
Hi Profs,
Previously I saw there the source settings somehow was set at gh-pages> I changed to master now. 

I attached the screenshot requested:
![image](https://user-images.githubusercontent.com/43993134/135265111-f16c60b0-a712-4f10-ac7f-da9e917ed122.png)

I also try to push a new commit to our remote Team repo:
![image](https://user-images.githubusercontent.com/43993134/135267244-427fb8f1-47c4-44a5-911e-432ba0670aaf.png)

But I do not know why there is no master branch detected at our remote Team repo?

I next go to my own fork of the Team repo, and create the same theme and check the recent push from my local is successfully updated  there:
![image](https://user-images.githubusercontent.com/43993134/135268707-3f70eb94-960f-4c46-9fed-f708901d8753.png)

**Comment by damithc** [comment]
> But I do not know why there is no master branch detected at our remote Team repo?

@gweeyc You may have to do a `fetch` first so that SourceTree can learn what branches your remote repo has.

**Comment by gweeyc** [comment]
HI Prof Damith,
Thanks for your tip, yes it is working now.
