### ISSUE TITLE
What does missing Java CI | passing icon mean?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#28]
Hi Profs,

R![image](https://user-images.githubusercontent.com/43993134/135276334-4aec6d7f-c742-4981-a936-b7b0e40b0bd3.png)

Now my team 4 has only this not yet pass the mark? May we know how to rectify this step?

Thank you!

**Comment by damithc** [comment]
@gweeyc It seems GitHub actions are not running for your repo. Add me as an admin to your team org so that I can take a look at your settings.

**Comment by gweeyc** [comment]
HI Prof Damith,
                            I have sent the invite as requested.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by damithc** [comment]
@gweeyc You need to click this button:

![image](https://user-images.githubusercontent.com/1673303/135296263-c0c3e4a1-2509-415a-8745-a95cdb0f2800.png)

**Comment by gweeyc** [comment]
Hi Prof,
Thanks! One more matter:

![image](https://user-images.githubusercontent.com/43993134/135387163-6eeaa8f3-ac57-48cd-9b42-dd3b1fd7260a.png)


I believe we will select Java CI for the workflow here? Now, the dashboard shows:

![image](https://user-images.githubusercontent.com/43993134/135387515-4ef235c5-fac3-41c0-a4e3-e74f36343f3b.png)

Do we now wait for the script auto-detect to update the board or we need to test it out with a sample?

**Comment by damithc** [comment]
> I believe we will select Java CI for the workflow here?

Yes.



> Do we now wait for the script auto-detect to update the board or we need to test it out with a sample?

It will run when there is a new commit. It is possible to manually rerun for past commits too. You can dig around a bit in the UI to find how to do that.

**Comment by gweeyc** [comment]
Ok, got it, thank you!
