### ISSUE TITLE
Github actions query fork after fork?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#29]
HI Profs,
I am a bit confused about github actions Java CI setting: one is set at the Team repo. But we have also a forked repo under our personal account. If we push various updates, like edit userguide, from our local clone, the github actions set for our personal account forked repo will update.

But when I create a PR to our Team repo on other issues not connected to the above descriptions, say only java codes, if the PR is merged, will the Team repo contain all the other kinds of non-java code commits from my forked repo (local account site) ?

**Comment by damithc** [comment]
@gweeyc it should be fine if each PR is based on a separate branch. Of course don't push garbage commits to the master branch of your fork -- if you do, those garbage commits will propagate to your team repo when you merge a PR from your fork to the team repo.

GitHub Actions simply checks the code -- it doesn't add anything.

**Comment by gweeyc** [comment]
Thanks. Will take note.
