### ISSUE TITLE
How to undo a fetch in sourcetree?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#3]
Hi Prof Damith,
                          when I want to add changes to my last commit, I open up sourcetree and wanted to push, but then I saw a pull blue arrow also highlighted, I am mystified as I did not change any thing on my remote end of my fork, only locally I edit my codes. Has this sudden pull notice come about because I checked the issue tracker (as asked) recently on my iP fork? 

So I try do a fetch first, hoping to check what is the change, but I am not familiar what is the next step to check it? So I decided to try to undo the fetch, but I find I do not know how to do this too, where can I find documentation in sourcetree? I check my remote fork, there is no change since last previous commit??

Now I have this situation:
![image](https://user-images.githubusercontent.com/43993134/130188078-19aae01e-4696-4eb3-aa06-312fe8095ffd.png)

I would like to get rid of the fetch, think stash first my latest changes and just pull, then push my latest commit that is all.

Or can I rebase as this snippet seems to suggest at my local working directory ip:
![image](https://user-images.githubusercontent.com/43993134/130189307-97bac80b-9533-4e0f-8b75-0a520b8bc91a.png)

Thank you for your kind help.

**Comment by damithc** [comment]
@gweeyc If you modify a commit locally _after_ you have pushed it to a remote, you will have a situation where the revision history graph is split two-ways, one for the modified commit you have locally and one for the original copy of that commit that exists in the remote repo. Is that what happened here?

To overwrite the original commit on the remote with your modified commit, you can do a force-push `git push -f origin master`

In general, try to avoid modifying commits if you have pushed them to a remote already.

**Comment by gweeyc** [comment]
HI Prof Damith,
Thanks for the advice, yeah I think I will not try another commit amend again.
                         I first do stage my edit Duke.java file, choose commit amend it in sourcetree so it will replace the most recent commit:
![image](https://user-images.githubusercontent.com/43993134/130197671-309c9b0c-a771-4ffd-b689-0b2bf8c53a4a.png)

As you can see in the png file, the Duke Leve-3: Mark as Done is waiting for me to push to remote to replace the one below it?

This is where I saw the blue pull arrow icon suddenly appearing for no reason. 
![image](https://user-images.githubusercontent.com/43993134/130198529-7c669633-dd95-4b17-a525-8d244e9292fd.png)

Normally one is to pull before push, my worry is if I pull, will the commit amend be gone and all the local changes? Will sourcetree stash auto for me as the pull-merge occurs so I can add the stash back on afterwards?

But I notice the stash button is greyed out after I have clicked fetch somehow, as seen in the screenshot below?
![image](https://user-images.githubusercontent.com/43993134/130198677-885859c8-73d8-4bad-9038-de64a52bf7e7.png)

Think whatever I do, I must deal with the pull issue first right? Then I just do a normal pull and that will get rid of the fetch issue, followed by the push is all I want.

Another way I was thinking is use the git command in bash: git rebase origin/master ? but will this mess up my commit amend, by replacing it, or creating another commit after it? Will this matter?

**Comment by gweeyc** [comment]
I manage to discard the problematic commit, so all goes back to previous latest working copy. Thank you.

**Comment by damithc** [comment]
@gweeyc Up arrow means you have one commit you haven't pushed (i.e., the commit you amended, which Git sees as a new commit altogether).
The down arrow means your remote has a commit that you don't have. That is the original copy of the commit.

The point is, after you amend a commit, the original copy and the updated commit are considered two entirely different commits, as they have different timestamps.

**Comment by gweeyc** [comment]
HI Prof Damith,
                           Ah, I see, then unlike command prompt git , Sourcetree suddent turn on of pull and push confuses people who just want to have commit amend?
So in this case, Sourcetree commit amend process is so confusing, so how do I go about completing the commit amend from this situation?

Anyway, I had reverted to the previous state, so my code is safe, just that I want to add in more changes to the latest commit part gets bogged down because of the above scenario.

Thank you again for the advice.
Gwee Yeu Chai

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by damithc** [comment]
@gweeyc if you were using CLI, you will not realize this problem until you try to push, at which point Git will give you an error message saying that your local and remote have diverged. 
Bottom line: if you amend commits _after_ pushing the commit to a remote, this will happen whichever the tool you use (SourceTree makes it visible earlier). The solution is to force-push to overwrite the remote copy with the local copy.

**Comment by gweeyc** [comment]
HI Prof Damith,
                            Thank you for the solution. Yes that has solved my commit amend issue. I just enabled safe force-with-lease feature in SourceTree and push force accordingly :
***@***.***

                               All is ok now, though I notice the overwritten commit Duke Level-3: Mark as Done is now an isolated red dot branch?
                               Can this outdated commit branch be safely deleted? Or just ignore it?

Thank you.
Gwee Yeu Chai
A0177960R

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by damithc** [comment]
> Can this outdated commit branch be safely deleted? Or just ignore it?

I think you can ignore it.
