### ISSUE TITLE
How to setup gradle for use of Guava Multimap?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#30]
HI Profs,
Like to check if later on I like to use Guava Library Multimap as data structure for storing my appointment dates (keys) and descriptions (values), how do I configure the Gradle dependencies, or if needed at all?

Are we allowed to use Guava library for our tp project?

Thanks!

**Comment by damithc** [comment]
@gweeyc 

> Are we allowed to use Guava library for our tp project?

Yes, allowed.


> Like to check if later on I like to use Guava Library Multimap as data structure for storing my appointment dates (keys) and descriptions (values), how do I configure the Gradle dependencies, or if needed at all?

I imagine it would be similar to how Gradle is configured for other third party libraries.
Also, some libraries provide instructions on how to add it using Gradle. Check if this library has such a help.

**Comment by damithc** [comment]
e.g., https://mvnrepository.com/artifact/com.google.guava/guava/11.0.2

**Comment by gweeyc** [comment]
HI Prof Damith,
Thanks a lot for the link. I will look into it when we reach the later stages definitely, for I think Multimap data structure gives superior performance than arraylist, for storing and searching appointment objects consisting of dates and string values of descriptions (many-to-many relationships).

**Comment by gweeyc** [comment]
Thanks and will note.
