### ISSUE TITLE
What is v1.0 issues and other labels?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#31]
HI Profs,
_I wonder what needs to be done for the following grey labels to be marked successful:_

![image](https://user-images.githubusercontent.com/43993134/136492256-0a43ec4e-defe-444c-8b6d-e46dc6f3ed3d.png)

_What is v1.0 setup? I already setup a v1.0 Milestone?_

![image](https://user-images.githubusercontent.com/43993134/136492551-3f1395fb-9e28-4ce8-ba4c-b73f02862339.png)

_For the following, I have setup a PR, yet it is not marked ok?_

![image](https://user-images.githubusercontent.com/43993134/136492729-2dd591bc-dc34-44bc-b79c-cb7dec33e623.png)

![image](https://user-images.githubusercontent.com/43993134/136492327-b00a4c3d-b85c-4620-85fe-c5d59364dc59.png)

Thank you!

**Comment by damithc** [comment]
@gweeyc You can click on the (i) icon near the student/team ID to find more details about what is expected for each deliverable.

First one is green now.
The PRs are counted after they are merged.

**Comment by gweeyc** [comment]
Thanks. Will check.
