### ISSUE TITLE
How to avoid the Java CI error when program prompts for user input and there is none?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#32]
HI Profs,

![image](https://user-images.githubusercontent.com/43993134/136644950-d39637bb-d74c-44ac-b780-952b45b474f5.png)

![image](https://user-images.githubusercontent.com/43993134/136644955-5134d114-89ac-43b2-b8f7-b9c5e1651f39.png)

I find the error reported a bit confusing, as this is a Java program without user interactions, how does one pass in one in the first instance? I like to check how to avoid this error?

Thank you!

**Comment by damithc** [comment]
@gweeyc This is a failure of I/O redirection tests, which are based on the files in your `text-ui-test` folder. You can try to run them locally first to see if the same problem happens.

**Comment by gweeyc** [comment]
Ok. Thanks, will take note.
