### ISSUE TITLE
Why my master branch cannot be merged with my personal work branch now?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#33]
Hi Profs,
According to the screenshot below:

![image](https://user-images.githubusercontent.com/43993134/136815824-606025fd-2560-4df5-a8a5-53ba21a09d30.png)

I want to merge my personal repo master branch to my personal branch, but there is grey-out instead in the drop down menu? Why is that?

Thank you!

**Comment by damithc** [comment]
@gweeyc you need to be on the receiving branch (which you are) and right-click on the branch that you want to merge i.e., the master branch. Seems you are right-clicking on the the branch you are already in.

**Comment by gweeyc** [comment]
Oh, my bad. Thank you Prof Damith, will take note!
