### ISSUE TITLE
What is this error referring to?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#34]
Hi Profs,
This is the only remaining error I always see after push to my remote working branch: there is still this error when I have checked that locally for my personal work branch, my expected and actual files are exact duplicates, down to the last newline presence? I have edited the text files according to latest version of my JustBook software?

![image](https://user-images.githubusercontent.com/43993134/136819042-bdd2c0c9-a004-4a4d-a165-d343c3791aa1.png)

My actual.txt:
![image](https://user-images.githubusercontent.com/43993134/136819180-d741ae86-c9a6-458f-a573-76865ab054e8.png)

My expected.txt:
![image](https://user-images.githubusercontent.com/43993134/136819260-5a21de67-0a60-4487-8ed9-187f4bf237f0.png)

Thank you for the help.

**Comment by damithc** [comment]
Check if you are creating a new Scanner in every iteration of the loop (you should not). Instead, create it once and use it till the end.

**Comment by gweeyc** [comment]
HI Prof Damith,
                         Thank you for your help, but I check my code, the scanner is not repeatedly defined:

![image](https://user-images.githubusercontent.com/43993134/136822793-34bc93bd-fc4c-476b-acff-2e3a7985d69d.png)

Are we allow to alter the starting template code?

Thanks!

**Comment by damithc** [comment]
@gweeyc yes, you may change the given code.

Your code will fail if there is only one input by the user (because you call in.nextLine() at least twice in the code). That's probably why the test fails.

**Comment by gweeyc** [comment]
Oh, ok, thank you very much. I've edited the test IO files, now all passed! Thanks!
