### ISSUE TITLE
How does the merge conflict with Team org repo work?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#35]
Hi Profs,
I've a question: I am not sure how the merge conflict works here:
![image](https://user-images.githubusercontent.com/43993134/136909794-8672ab68-8f32-496b-8988-5837b7071de2.png)

Let's assume the master in Team Repo is an earlier version. I did my personal work branch and created the PR to merge with Team Org Repo. There will definitely be merge conflict notice. This is the part I am unclear: we can do the above steps as shown in the screen capture, locally I may resolve the conflict, however the Team Org Repo still sits there as it is, when I merge into it, the conflict still exists there in the Team Org Repo? How do I resolve that?

Thank you for the clarification!

**Comment by damithc** [comment]
@gweeyc 
1. When deconflicting locally, you should **do the deconflicting in your branch, not the master branch** i.e., merge master to your branch, not the other way around. That means the code needed to reverse the conflict is now in your branch.
2. After you push your branch to your fork, the PR will no longer show the conflict. Merging that PR will not cause any conflicts either, as the de-conflicting code is in the branch you will be merging.

**Comment by gweeyc** [comment]
Thank you, noted!
