### ISSUE TITLE
Java CI windows-latest build seemed stuck now every time?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#36]
HI Profs,

I found now every time I push from my local work branch, as the PR to Team Repo gets updated, Java CI will get stuck every time for a long time at windows-latest build:
![image](https://user-images.githubusercontent.com/43993134/137109187-5155b3b9-d45a-402a-bf9c-4205968288ed.png)

![image](https://user-images.githubusercontent.com/43993134/137108488-529792a3-3160-4f6d-abd0-7cc54ec9526f.png)

Later when I check, there is a white-grey screen that says test failed, there is no usual results of test logs at all?
![image](https://user-images.githubusercontent.com/43993134/137108895-404c5a9a-8eb1-4d54-a030-e48ce1860b61.png)

![image](https://user-images.githubusercontent.com/43993134/137108995-7b96b0be-d7d8-4692-93f3-6bfa4cf72ebf.png)

Thank you for the verification.

**Comment by damithc** [comment]
It's a GitHub problem @gweeyc 
https://www.githubstatus.com/

![image](https://user-images.githubusercontent.com/1673303/137109716-3c786909-ff62-4c6a-8509-04beefe736e7.png)

**Comment by gweeyc** [comment]
Oh, yeah, guess as much. Thank you!

**Comment by gweeyc** [comment]
Hi Prof Damith,
                          All tests working now! Thanks again!

Gwee Yeu Chai

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
