### ISSUE TITLE
For JUnit 5 parameterizedTest config and latest version compatible?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#37]
HI Profs,
For JUnit 5 latest version is 5.8.1, do we need to update to this version? Also for parameterized tests Gradle dependencies config:

testCompile("org.junit.jupiter:junit-jupiter-params:5.8.1")

Can we include the above line in our current build.gradle file? Will it cause conflict?

Thank you.

**Comment by damithc** [comment]
You may use a different version of JUnit if you wish @gweeyc It's your team's decision. You can give it a try.

**Comment by gweeyc** [comment]
Done. Thanks!
