### ISSUE TITLE
Can we change Duke.java to our JustBook.java for our JustBook App?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#38]
Hi Profs,
Our team wants to know do we retain the Duke.java file name or can we rename it to JustBook.java? Where else do we need to change for this to work? For My PR test run at Github shows the error precisely we change the Duke.java naming?

![image](https://user-images.githubusercontent.com/43993134/137170487-15a61a25-bd61-4c77-afd0-fdcff15c3e3e.png)

Thank you.

**Comment by damithc** [comment]
@gweeyc if you change the name of the main class, you need to update build.gradle too.

**Comment by gweeyc** [comment]
HI Prof Damith,
Thanks for the suggestion, so I need to change here? :
![image](https://user-images.githubusercontent.com/43993134/137174493-d040dcc9-9531-4cfe-8cab-68464c9b892d.png)

**Comment by damithc** [comment]
Yes, can change both. The second one is the name of the generated JAR file.

**Comment by gweeyc** [comment]
Hi Prof Damith,
Thank you for all the help! All works out very well. Will take note.
