### ISSUE TITLE
JUnit 5 using latest version but got this Gradle warning?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#39]
HI Profs,
I updated the dependency to JUnit 5.8.1 latest version but got this warning:
![image](https://user-images.githubusercontent.com/43993134/137173660-5859ec8f-88c2-4bdc-be05-d1f99f2cfa52.png)

I set the dependencies as 👍 
![image](https://user-images.githubusercontent.com/43993134/137173823-b4af4350-fd3d-4bfd-a732-95915d4063d5.png)

Later I am planning to use @ParameterizedTest that's why I want the second last configure. Shall I ignore the warning or need to change something else?

Thank you!

**Comment by damithc** [comment]
You can ignore that warning @gweeyc

**Comment by gweeyc** [comment]
Roger! Thanks!
