### ISSUE TITLE
Java has no function pointers to optimize similar functions?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#4]
Hi Profs, classmates,

I come across a case where two functions differ only by 1 line of code:

![image](https://user-images.githubusercontent.com/43993134/130614232-4839f3fe-609a-410a-a5e8-24c8c9f336a1.png)

I wish to optimize the code via maybe function pointers or so but I find Java has no such thing.

How can I proceed to collapse the two functions into one without too much codes generated in return?
The Event class extends Deadline here.
I first thought of creating another function say addTimedTask() & just use procedural if-else to single out the two differing lines...but there is that extra check. I wonder is there another better way, or what is the best practice here?

Thank you.

**Comment by gweeyc** [comment]
I think I can leave it as it is, not a big problem for a samll program

**Comment by damithc** [comment]
There are no function pointers in Java @gweeyc 
Yes, these two are probably two small to worth the effort of unifying.
