### ISSUE TITLE
v1.0 PRs Workflow

### ISSUE THREAD

**Issue by jr-mojito** [nus-tic4001-AY2122S1/forum#40]
I've a question regarding workflow of v1.0 PRs. 
Current workflow : PR from Fork repo <master>  to Team Repo <master>
But the tp progress can detect the v1.0 PRs.
Should I change PR workflow to: PR from Fork repo <branch-add-junit>  to Team Repo <master> ?
Thank you.

**Comment by damithc** [comment]
@jr-mojito you gave the same workflow for both options :-)

Which PR is not being detected? Note that only merged PRs are detected by the dashboard. Furthermore, the PR should come from a separate branch, not the master branch (as per the forking workflow).

**Comment by jr-mojito** [comment]
Opps.. the branch name deleted at the questions.

Current workflow : PR from Fork repo `master` to Team Repo `master` (not detected after merged PR)
Should I change PR workflow to: PR from Fork repo `branch-add-new` to Team Repo `master`?

**Comment by damithc** [comment]
> Should I change PR workflow to: PR from Fork repo `branch-add-new` to Team Repo `master`?

Yes @jr-mojito as per the forking workflow. More details https://nus-tic4001-ay2122s1.github.io/website/admin/appendixE-gitHub.html#tp-workflow

**Comment by jr-mojito** [comment]
Thank you Professor.
