### ISSUE TITLE
Release done before midnight yesterday but label not updated this morning?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#41]
HI Profs,
![image](https://user-images.githubusercontent.com/43993134/137434169-31b85c10-d611-4e97-893c-f43dc5e2a4f5.png)

Our Team 4 released the JustBook App v1.0 around 11:55pm yesterday. This morning I check and see the tp Dashboard was updated around 9:20 am this morning but I see this:

![image](https://user-images.githubusercontent.com/43993134/137433934-71959061-7b3b-4465-8405-9760b92afb18.png)

Wonder why it is not updated? Have we configured wrongly somewhere?

Thank you!

**Comment by damithc** [comment]
It was due to an incorrect date setting in the dashboard. Should be fine now. Thanks for letting us know @gweeyc

**Comment by gweeyc** [comment]
Roger.
