### ISSUE TITLE
Is this a github action issue again?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#42]
Hi Profs,

I recently pushed direct into the Team Repo master (add assert and logging function), and I see this on github:
![image](https://user-images.githubusercontent.com/43993134/137439333-dad931ff-1206-4cc3-8c61-bc66cde21c25.png)

In my email I receive this:
![image](https://user-images.githubusercontent.com/43993134/137439381-b7b1e8f9-9abc-4cb9-909a-893c4eb619eb.png)

But my local repo action has all three green ticks, no problems?

Thank you for the advice.

**Comment by damithc** [comment]
@gweeyc Could be caused by a temporary network problem. Try rerunning CI.

**Comment by gweeyc** [comment]
Yes, just a temporary issue. Thanks!
