### ISSUE TITLE
Repo-sense detection of DG code contributions not showing?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#44]
Hi Profs,

![image](https://user-images.githubusercontent.com/43993134/138452268-6b2e488a-f96d-4e1c-be06-b04fe4e29c2c.png)

![image](https://user-images.githubusercontent.com/43993134/138452373-f678dc10-70cf-4cb2-b1c4-31c8bf0e9cfc.png)

We did the first draft of the Team Repo DG but when I check for the Repo-sense code report section it does not show 'tracked'?
![image](https://user-images.githubusercontent.com/43993134/138452675-72124928-ce9f-439d-8ec1-008453da7657.png)

![image](https://user-images.githubusercontent.com/43993134/138452811-66d82c35-8845-4e7a-8e4a-9a49640f4be9.png)
No Developer Guide section reported?

Thank you!

**Comment by damithc** [comment]
@gweeyc The code dashboard updates about once a day. You can check the last updated time at the bottom of that page.

**Comment by gweeyc** [comment]
HI Prof,
Confirmed there is no detection of my DG Draft code contribution:

[This page was last updated on 2021-10-23 @11:42]
![image](https://user-images.githubusercontent.com/43993134/138555917-ba35934e-2cd0-48c4-8b57-a47299202098.png)

But for the tp dashboard code base, I do see the detected the DG code contributions:
![image](https://user-images.githubusercontent.com/43993134/138556043-c4993d59-9fba-4d5f-9b58-268f6dfd2653.png)


Thank you for your advice.

**Comment by damithc** [comment]
@gweeyc based on your screenshot, seems `DG draft` is already green? It is the `UG draft` that is not green yet.

**Comment by gweeyc** [comment]
Oh, I got it now, haha, I always got problem reading similar words as I am far sighted! Thank you!
