### ISSUE TITLE
About info?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#45]
HI Profs,
 I am wondering what is to be filled in here in the github repo page :

![image](https://user-images.githubusercontent.com/43993134/139274724-34136d52-07d8-4829-8901-b19591ba0403.png)

Thank you.

**Comment by damithc** [comment]
Up to you @gweeyc Feel free to submit any appropriate info, as guided by the GitHub interface.
OK to leave it blank too.

**Comment by gweeyc** [comment]
Noted and thank you.
