### ISSUE TITLE
The tp Dashboard no update issue

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#46]
HI Profs,
According to this dashboard screenshot:
![image](https://user-images.githubusercontent.com/43993134/139383435-c4571535-af3e-413a-a3e6-018487171135.png)

It is not showing the correct status of my UG, as I have submitted multiple lines into it yesterday or earlier?

Thank you for the solution.

**Comment by damithc** [comment]
I'll check this and get back to you later @gweeyc

**Comment by gweeyc** [comment]
Thank you Now it has updated.
