### ISSUE TITLE
Intellij how to create a package and assign all the files to it?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#5]
HI Prof Damith,

I created a package under the source folder ip.duke but I do not see Intellij automatically put all my java files under it?

![image](https://user-images.githubusercontent.com/43993134/130648942-c1638c81-ceca-4f29-9da8-34384c314278.png)

How do I put all my java files under this package?

Thank you!

**Comment by damithc** [comment]
@gweeyc You can try one of these (inside Intellij):
* Ctrl+click to select those Java files and drag-and-drop into the package folder
* Right-click on the Java file and select 'Refactor' -> 'Move'
* Manually move files and add the `package ip.duke` statement at the top of each file

**Comment by gweeyc** [comment]
HI Prof Damith,
Thank you for the helpful instructions. I find Ctrl _ click is best as I find if I do it individually, Intellij at times will insert at random lines into the unmigrated files(s) found - to seemingly quote the right object references!

Thanks again!
