### ISSUE TITLE
During tests, issues found with output does not capture what is entered on screen?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#7]
Hi Prof Damith,
I can run the runtest.bat fine but the output is problematic for me:

ACTUAL.TXT:
![image](https://user-images.githubusercontent.com/43993134/130807913-47fdc89b-0ed7-43bc-bcab-77068b732a32.png)

EXPECTED.TXT:
![image](https://user-images.githubusercontent.com/43993134/130808177-2209b50b-b2de-4a50-a61c-459fb436684f.png)

It seems what user input has been taken out by Java Scanner and the lines output and the space between MasterOm and LisGenie do not align with what I have actually programmed in the Duke.java files? I suspect it may be due to the Scanner function again?

Here is the actual output from the runtest.bat:
![image](https://user-images.githubusercontent.com/43993134/130809897-edb65f41-a2a6-4677-b7b6-b74d9fe0515f.png)

Is there a way to solve for the lines misalignment? If I take out the lines say, I guess I can adjust the expected file to get rid of the spaceing problems between MasterOm and LisGenie, then I think the problem may be solved?

Thank you for the advice!

**Comment by damithc** [comment]
@gweeyc Yes, the output file will not contain user inputs. 
In practice, we don't normally construct the EXPECTED.TXT file by hand.
In the first round of running the test, you can let it fail. Then, you can examine the ACTUAL.TXT manually and if the content seems alright, copy it over to the EXPECTED.TXT 
After that, future runs should pass, until the output changes  again. When that happens, you can check the ACTUAL.TXT file again and if the change is acceptable, copy over the contain again to the EXPECTED.TXT.

**Comment by gweeyc** [comment]
Thanks! Got it.
