### ISSUE TITLE
What is "2t" shown beside a master label?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#8]
HI Prof Damith,
I was trying out the samplerepo-things branching exercise:

![image](https://user-images.githubusercontent.com/43993134/131248237-f8736836-4027-48cb-b761-bf594d6c9a62.png)

I saw there is a 2t beside the master branch label at the top. What does this "2t" mean or point to?

Thank you!

**Comment by damithc** [comment]
@gweeyc that's an upward arrow, not a `t`.
It means there are two commits in the current branch that you haven't pushed to the remote repo yet. Note how `origin/master` label is two commits behind your `master` label.

**Comment by gweeyc** [comment]
HI Prof Damith,

Well, looks like my aging eyesight likes to smooth out the tiny arrow to a 't' here!

Noted and thanks again!
