### ISSUE TITLE
Setter methods in Java made public to access from a controller program?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#9]
Hi Prof Damith,
I notice often in a class like controller class file Duke.java, say under a ip.duke package, often, it is not a subclass of any other classes in the program.

Then, if we have a protected setter method to a private field created say in Task class in the ip.duke.task package say, and we call this setter from Duke.java file: but though we can import the ip.duke.task into Duke.java, to call the setter method, it will force one to change the protected access modifier of the setter method to a public one before it can even be accessed from Duke.java file? 

Does it make sense to have a public setter method to a private field of a class made available? Will it be better if one can restrict the call of that setter method via a private method in the controller class only?

Thank you

**Comment by boydanderson** [comment]
Hi Gwee.

Good question. So to your first point, we can see that the `protected` access modifier means that a member can only be accessed within its own package or by a subclass of its class in another package. You can find these modifiers here in the [notes](https://nus-tic4001-ay2122s1.github.io/website/schedule/week4/topics.html#w4-5-java-access-modifiers). As your driver/controller class is in a different package it therefore needs to be public.

With regards to your first question, it is ok to have public setter methods? This is a very design specific question. Yes, in some situations this is ok. In your setter method you may have to check if what is being passed as input is correct for your class. In other cases, you might be breaking information hiding of your class (exposing implementation details of your class). 

Your second question: What if it is only used only by a controller class? The same logic above applies as anyone could use your class in their program.

**Comment by gweeyc** [comment]
Thanks Prof Boyd, will take note.
